# Generated by Django 5.2.1 on 2026-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('monthly', 'Miesięczna'), ('yearly', 'Roczna')], default='monthly', max_length=10),
        ),
    ]
